name: Publish Services to Nuget.org

on:
  workflow_dispatch
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: '10.x'
          
    - name: Install dependencies
      run: |
        dotnet restore src/ActiveDirectory/ActiveDirectory.csproj
        dotnet restore src/Serilog/Serilog.csproj
        dotnet restore src/Caching/Caching.csproj
        dotnet restore src/FileGenerator/FileGenerator.csproj
        dotnet restore src/Mail.Contracts/Mail.Contracts.csproj
        dotnet restore src/SmtpMail/SmtpMail.csproj
        dotnet restore src/Graph/Graph.csproj
        
    - name: Build
      run: |
        dotnet build src/ActiveDirectory/ActiveDirectory.csproj --configuration Release --no-restore
        dotnet build src/Serilog/Serilog.csproj --configuration Release --no-restore
        dotnet build src/Caching/Caching.csproj --configuration Release --no-restore
        dotnet build src/FileGenerator/FileGenerator.csproj --configuration Release --no-restore
        dotnet build src/Mail.Contracts/Mail.Contracts.csproj --configuration Release --no-restore
        dotnet build src/SmtpMail/SmtpMail.csproj --configuration Release --no-restore
        dotnet build src/Graph/Graph.csproj --configuration Release --no-restore
        
    - name: Publish to Nuget.org
      run: |
        rm -rf nuget/

        dotnet pack --no-build src/ActiveDirectory/ActiveDirectory.csproj --configuration Release --output nuget
        dotnet pack --no-build src/Serilog/Serilog.csproj --configuration Release --output nuget
        dotnet pack --no-build src/Caching/Caching.csproj --configuration Release --output nuget
        dotnet pack --no-build src/FileGenerator/FileGenerator.csproj --configuration Release --output nuget
        dotnet pack --no-build src/Mail.Contracts/Mail.Contracts.csproj --configuration Release --output nuget
        dotnet pack --no-build src/SmtpMail/SmtpMail.csproj --configuration Release --output nuget
        dotnet pack --no-build src/Graph/Graph.csproj --configuration Release --output nuget
        
        dotnet nuget push nuget/*.nupkg -k '${{ secrets.NUGET_API_KEY }}' --skip-duplicate -s https://api.nuget.org/v3/index.json
