name: Publish Blazor to Nuget.org

on:
  workflow_dispatch
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: '10.x'

    - name: Install dependencies
      run: |
        dotnet restore src/Blazor/Blazor.csproj
        dotnet restore src/Blazor.MudBlazor.Extra/Blazor.MudBlazor.Extra.csproj
        dotnet restore src/Blazor.FluentBlazor.Extra/Blazor.FluentBlazor.Extra.csproj

    - name: Build
      run: |
        dotnet build src/Blazor/Blazor.csproj --configuration Release --no-restore
        dotnet build src/Blazor.MudBlazor.Extra/Blazor.MudBlazor.Extra.csproj --configuration Release --no-restore
        dotnet build src/Blazor.FluentBlazor.Extra/Blazor.FluentBlazor.Extra.csproj --configuration Release --no-restore

    - name: Publish to Nuget.org
      run: |
        rm -rf nuget/

        dotnet pack --no-build src/Blazor/Blazor.csproj --configuration Release --output nuget
        dotnet pack --no-build src/Blazor.MudBlazor.Extra/Blazor.MudBlazor.Extra.csproj --configuration Release --output nuget
        dotnet pack --no-build src/Blazor.FluentBlazor.Extra/Blazor.FluentBlazor.Extra.csproj --configuration Release --output nuget

        dotnet nuget push nuget/*.nupkg -k '${{ secrets.NUGET_API_KEY }}' --skip-duplicate -s https://api.nuget.org/v3/index.json
